"""Allow multiple tests

Revision ID: 427b45702796
Revises: 4458e99a0758
Create Date: 2015-03-23 18:32:39.277749

"""

# revision identifiers, used by Alembic.
revision = '427b45702796'
down_revision = '4458e99a0758'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_test', sa.Column('parent_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_test', 'parent_id')
    ### end Alembic commands ###
